### ISSUE TITLE
bastille-lib.pl named incorrectly, bastille-manager-lib.pl is required

### ISSUE THREAD

**Issue by jemail99** [JRGTH/bastille-manager-webmin-module#1]
webmin version: 1.984
bastille-manager version: 0.4.3

Click the cog, once the configuration page loads the following error is shown:
`Require bastille-manager/bastille-manager-lib.pl failed : Died at (eval 234) line 1.`

Solution:
Rename bastille-lib.pl to bastille-manager-lib.pl

**Comment by JRGTH** [comment]
Hello, thanks for the report, looks like on recent Webmin release the lib file need to be named similar to the module name regardless of the explicit `require './bastille-lib.pl';`

I will update this module today.

**Comment by JRGTH** [comment]
Hello, this module has been updated and released at SourceForge.

**Comment by jemail99** [comment]
You can close this issue as the latest version has corrected the issue.
